name: Daily IPO Fund Bot

on:
  schedule:
    - cron: '30 4 * * *'   # 10:00 IST daily
  workflow_dispatch:       # manual trigger

jobs:
  ipo-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install playwright python-telegram-bot
          playwright install
      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MIN_GMP: ${{ vars.MIN_GMP }}
          FUND_PER_IPO_LAKH: ${{ vars.FUND_PER_IPO_LAKH }}
        run: python ipo_bot.py
